# Generated by Django 3.0.6 on 2020-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechos',
            name='jornal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trechos',
            name='video_assunto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
